// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjpdjTQbfMyKz39ASQTiaCdIWcB0Ri6XM',
    appId: '1:197561823479:web:e9ef3b1a803efb1e1ba3f2',
    messagingSenderId: '197561823479',
    projectId: 'tdmu-smartdoc',
    authDomain: 'tdmu-smartdoc.firebaseapp.com',
    storageBucket: 'tdmu-smartdoc.firebasestorage.app',
    measurementId: 'G-1FN9V7TS65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7WUoqAGNQ5twZ__FNe2IoEQyf48hnWus',
    appId: '1:197561823479:android:420afd6aa059223f1ba3f2',
    messagingSenderId: '197561823479',
    projectId: 'tdmu-smartdoc',
    storageBucket: 'tdmu-smartdoc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuRA48Z9ym_KAbvo3wHPlEKfXTbik30Kk',
    appId: '1:197561823479:ios:6450dc8f8e9ddd981ba3f2',
    messagingSenderId: '197561823479',
    projectId: 'tdmu-smartdoc',
    storageBucket: 'tdmu-smartdoc.firebasestorage.app',
    iosBundleId: 'com.example.tdmuSmartdocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuRA48Z9ym_KAbvo3wHPlEKfXTbik30Kk',
    appId: '1:197561823479:ios:6450dc8f8e9ddd981ba3f2',
    messagingSenderId: '197561823479',
    projectId: 'tdmu-smartdoc',
    storageBucket: 'tdmu-smartdoc.firebasestorage.app',
    iosBundleId: 'com.example.tdmuSmartdocs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjpdjTQbfMyKz39ASQTiaCdIWcB0Ri6XM',
    appId: '1:197561823479:web:ca1fa64e82e21ae11ba3f2',
    messagingSenderId: '197561823479',
    projectId: 'tdmu-smartdoc',
    authDomain: 'tdmu-smartdoc.firebaseapp.com',
    storageBucket: 'tdmu-smartdoc.firebasestorage.app',
    measurementId: 'G-T61JSHEL8X',
  );
}
